config/routes.rb
Rails.application.routes.draw do
  
  get 'all_posts/new'

  root "welcome#index"
  resources :profiles
  resources :posts

  devise_for :users

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_one :profile, :through => :user

	validates :picture, :description, :presence => true

	has_attached_file :picture, :styles => { :large => "600x600", :medium => "300x300", :thumb => "100x100>" }
	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_many :posts, :through => :user

	has_attached_file :avatar, :styles => { :large => "600x600", :medium => "300x300", :thumb => "100x100>"}
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	validates :username, :avatar, :presence => true
	validates :username, length: {
		minimum: 2,
		maximum: 15
	}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_one :profile, dependent: :destroy
         has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :check_profile_exists

  protected

  def check_profile_exists
  	if user_signed_in? && !current_user.profile
  		redirect_to new_profile_path
  	end
  	
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]
  before_action :set_post, only: [:show, :destroy]
  before_action :require_auth, only: [:destroy]


  def new
  	@post = Post.new
  end

  def show
  	
  end

  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id

  	respond_to do |format|
  		if @post.save
  			format.html { redirect_to @post }
  		else
  			format.html { render :new}
  		end
  end
end

def destroy
	@post.destroy
	respond_to do |format|
		format.html { redirect_to '/', :notice => 'Post delete successful'}
	end
end

private

def require_auth
	if @post.user_id != current_user.id
		flash[:alert] ="You are not authorized"
		redirect_to :back
	end
end

def set_post
	@post = Post.find(params[:id])
	
end

def post_params
	params.require(:post).permit(:description, :picture)
end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :check_profile_exists, :only => [:new, :create]
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  def index
  	redirect_to current_user.profile
  end

  def new
  	@profile = Profile.new
  end

  def edit
  	
  end

  def show
  	@posts = @profile.user.posts
  end

  def create
  	@profile = Profile.new(profile_params)
  	@profile.user_id = current_user.id
  	
  	respond_to do |format|
  		if @profile.save
  			format.html { redirect_to profiles_path, notice: 'Profile was created'}
  		else
  			format.html { render: new}
  		end
  end
end

def update
	respond_to do |format|
		if @profile.update(profile_params)
			format.html { redirect_to profiles_path, notice: 'Profile was updated'}
		else
			format.html { render :edit}
		end
	end
end

private
	def set_profile
		@profile = Profile.find(params[:id])
	end

	def profile_params
		params.require(:profile).permit(:username, :avatar)
		
	end
end

app/controllers/welcome_controller.rb
#this is the view for cancancan
class WelcomeController < ApplicationController
  def index
  	@posts = Post.all.order('created_at desc')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediumClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-inverse">
		<div class="container">
			<div class="navbar-header">
				<%= link_to 'iCan', root_path, class: 'navbar-brand' %>
			</div>
			<div id="navbar">
				<ul class="nav navbar-nav">
				</ul>
				
			</div>
		</div>
	</nav>

<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<div class="well well-sm">
  <p>
    <span class="post-creator" style="background-image: url(<%= post.profile.avatar(:thumb) %>)"></span>
    <strong><%= link_to post.profile.username, post.profile %></strong>
    <span style="float: right; font-size: 8pt;"><%= time_ago_in_words(post.created_at) %> ago</span>
  </p>

  <div id="postPic" style="background-image: url(<%= post.picture.url %>)">
    <% if user_signed_in? && current_user.id == post.user_id %>
      <%= button_to "Delete", post_path(post.id), data: { confirm: "Are you sure?" }, :class =>'btn btn-danger post-destroy', method: :delete %>
    <% end %>
  </div>
  <hr />
  <p>
    <span class="post-creator" style="background-image: url(<%= post.profile.avatar(:thumb) %>)"></span>
    <strong><%= link_to post.profile.username, post.profile %></strong>
    <%= post.description %>
  </p>
</div>

app/views/posts/_smallpost_html.erb
div class="col-md-3 col-sm-6 col-xs-12 post-sm">
  <div class=" well well-sm ">
    <p>
      <span class="post-creator" style="background-image: url(<%= post.profile.avatar(:thumb) %>)"></span>
      <strong><%= link_to post.profile.username, post.profile %></strong>
      <span style="float: right; font-size: 8pt;"><%= time_ago_in_words(post.created_at) %> ago</span>
    </p>

    <div id="postPic" style="background-image: url(<%= post.picture.url %>);" onclick="document.location.href='/posts/<%= post.id %>'">
      
    </div>
    <hr />
    <p>
      <strong><%= link_to post.user.profile.username, post.user.profile %></strong> - <%= post.description %>
    </p>
  </div>

</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel">
        <h3>New Post</h3>
        <%= form_for(@post) do |f| %>
        <% if @post.errors.count > 0 %>
          <div class="alert alert-danger">
            <% @post.errors.full_messages.each do |e| %>
            <ul>
              <li><%= e %></li>
            </ul>
            <% end %>
          </div>
        <% end %>
        <div class="field form-group">
          <%= f.text_field :description, :class => 'form-control', :placeholder => "Description" %>
        </div>
        <div class="field form-group">
          <%= f.file_field :picture %>
        </div>
        <%= f.submit "Make it!", :class => 'btn btn-primary' %>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <%= render 'posts/post', :post => @post %>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel">
        <h3>Edit Profile</h3>
        <%= form_for(@profile) do |f| %>
        <% if @profile.errors.count > 0 %>
          <div class="alert alert-danger">
            <% @profile.errors.full_messages.each do |e| %>
            <ul>
              <li><%= e %></li>
            </ul>
            <% end %>
          </div>
        <% end %>
        <div class="field form-group">
          <%= f.label :username %>
          <%= f.text_field :username, :class => 'form-control', :placeholder => "Username" %>
        </div>
        <div class="field form-group">
          <%= f.label :avatar %>
          <%= f.file_field :avatar %>
        </div>
        <%= f.submit "Let's go!", :class => 'btn btn-primary' %>
        <% end %>


    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<div class="row">
  <img src="/uploads/<%= @profile.profile_pic %>" alt="" />
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel">
        <h3>Welcome to braInstagram!</h3>
        <p>
          We're going to have to ask you a few questions.
        </p>
        <p>
          Namely: what should we call you?
        </p>
        <%= form_for(@profile) do |f| %>
        <% if @profile.errors.count > 0 %>
          <div class="alert alert-danger">
            <% @profile.errors.full_messages.each do |e| %>
            <ul>
              <li><%= e %></li>
            </ul>
            <% end %>
          </div>
        <% end %>
        <div class="field form-group">
          <%= f.text_field :username, :class => 'form-control', :placeholder => "Username" %>
        </div>
        <p>
          Lastly (and we're sorry if this is a bit creepy), but what do you look like?
        </p>
        <div class="field form-group">
          <%= f.file_field :avatar %>
        </div>
        <%= f.submit "Let's go!", :class => 'btn btn-primary' %>
        <% end %>


    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="well well-sm" style="background: url(<%= @profile.avatar.url(:large) %>); background-size: cover; min-height: 225px; min-width: 225px; background-position: center;">

    </div>
  </div>
  <div class="col-md-9">
    <div class="page-header">
      <h2><%= @profile.username %></h2>
      <h5>Member for <%= time_ago_in_words(@profile.created_at) %> - <%= @profile.posts.count %> posts</h5>
    </div>
    <% if current_user.profile.id == @profile.id %>
      <%= link_to 'Edit my Profile', edit_profile_path %>      
    <% end %>

  </div>
</div>

<div class="row">
  <% @posts.each do |p| %>
    <%= render 'posts/smallpost', :post => p %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="row">

<h1>Welcome#index</h1>

<% @posts.each do |p| %>
	<%= render 'posts/smallpost', :post => p %>
<% end %>
</div>

app/views/welcome/secret.html.erb
<h1>Welcome#secret</h1>
<p>Find me in app/views/welcome/secret.html.erb</p>